name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: |
          date
  ls_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print content
        run: |
          ls -l
