name: Hello World!

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: part11/full-stack-open-pokedex
    
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: |
          date
  ls_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print content
        run: |
          ls -l
